image: python:3.9-alpine

pipelines:
  default:
    - step:
        name: Build and Deploy
        script:
          - apk add --no-cache --virtual .build-deps gcc musl-dev
          - apk del .build-deps
          - docker.compose ups
