pipelines:
  default:
    - step:
        name: Sync GitHub Mirror
        image: alpine/git:latest
        clone:
          enabled: false
        script:
          - git clone --bare git@bitbucket.org:visitor1/visitor-back.git
          - cd visitor-back.git
          - git push --mirror git@github.com:Alejocas17/vistor.git